### ISSUE TITLE
No need to track loaded state.

### ISSUE THREAD

**Issue by Carreau** [DlangScience/PydMagic#1]
```
def load_ipython_extension(ip):
    global _loaded
    if not _loaded:
        ip.register_magics(PydMagics)
        _loaded = True
```

Any recent enough IPython take care of that for you.  Define a `unload_ipython_extension` if you want a specific step to be take care of during reload.

**Comment by John-Colvin** [comment]
Thanks for the advice

https://github.com/DlangScience/PydMagic/pull/5

**Comment by John-Colvin** [comment]
Fixed by https://github.com/DlangScience/PydMagic/pull/7
