### ISSUE TITLE
unicode vs str problem on hello world example

### ISSUE THREAD

**Issue by Laeeth** [DlangScience/PydMagic#13]
Hi John.

I am using arch linux with python 2.7.9 (Anaconda) on 64 bit machine.

%%pyd

@pdef!() string hello() {
    return "Hello World!";
}

---

TypeError                                 Traceback (most recent call last)
<ipython-input-15-2db37930ea0c> in <module>()
----> 1 get_ipython().run_cell_magic(u'pyd', u'', u'\n@pdef!() string hello() {\n    return "Hello World!";\n}')

/home/laeeth/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2160             magic_arg_s = self.var_expand(line, stack_depth)
   2161             with self.builtin_trap:
-> 2162                 result = fn(magic_arg_s, cell)
   2163             return result
   2164 

/home/laeeth/.ipython/extensions/pyd_magic.pyc in pyd(self, line, cell)

/home/laeeth/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, _a, *_k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, _a, *_k: f(_a, *_k)
    194 
    195         if callable(arg):

/home/laeeth/.ipython/extensions/pyd_magic.pyc in pyd(self, line, cell)
    149 
    150             with io.open(pyd_dub_file, 'w', encoding='utf-8') as f:
--> 151                 f.write(json.dumps(pyd_dub_json)+'\n')
    152             try:
    153                 os.remove(os.path.join(lib_dir, 'dub.selections.json'))

TypeError: must be unicode, not str

**Comment by John-Colvin** [comment]
Should be fixed by https://github.com/DlangScience/PydMagic/pull/15, feel free to re-open if the problem persists.

**Comment by Laeeth** [comment]
Thank you!  Works great.  (I had to start a new notebook and then all worked fine).
Really very useful, even for simple stuff.  Eg I find D parsing of data files much more agreeable than via python.  (In part, because that's what I use, and I have helpers already set up).
