### ISSUE TITLE
no property needs_shim, call

### ISSUE THREAD

**Issue by Laeeth** [DlangScience/PydMagic#16]
Am I doing something wrong ?

%%pyd
@pdef!() struct Test
{
    double[] mynumbers;
    string[] mystrings;
}

@pdef!() Test makeTest(double a)
{
    Test t;
    t.mynumbers=[1.0,2.0,3.9,4.2];
    t.mystrings=["why","are2","we","waiting"];
    return t;
}

Building _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275 ~master configuration "library", build type debug.
Compiling using dmd...
registering module _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275.object
not registered
registering module _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275.ppyd
not registered
registering module _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275.Test
as aggregate type
registering Test.mynumbers
with class/struct parent
as member
registering Test.mystrings
with class/struct parent
as member
../../home/laeeth/.dub/packages/pyd-0.9.7/infrastructure/pyd/class_wrap.d(1500): Error: no property 'needs_shim' for type 'void'
../../home/laeeth/.dub/packages/pyd-0.9.7/infrastructure/pyd/class_wrap.d(1503): Error: no property 'call' for type 'void'
../../home/laeeth/.dub/packages/pyd-0.9.7/infrastructure/pyd/class_wrap.d(1500): Error: no property 'needs_shim' for type 'void'
../../home/laeeth/.dub/packages/pyd-0.9.7/infrastructure/pyd/class_wrap.d(1503): Error: no property 'call' for type 'void'
../../home/laeeth/.dub/packages/ppyd-0.1.1/ppyd.d(110): Error: template instance pyd.class_wrap.wrap_class!(Test, void, void) error instantiating
../../home/laeeth/.dub/packages/ppyd-0.1.1/ppyd.d(176):        instantiated from here: registerAggregateType!("Test", _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275)
../../home/laeeth/.dub/packages/ppyd-0.1.1/ppyd.d(203):        instantiated from here: registerModuleScopeSymbol!("Test", _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275)
../../home/laeeth/.cache/ipython/pyd/_pyd_magic_7c8a7283575fef42aa3d0f1dc803a275/_pyd_magic_7c8a7283575fef42aa3d0f1dc803a275.d(5):        instantiated from here: registerAll!(_pyd_magic_7c8a7283575fef42aa3d0f1dc803a275)
FAIL ../../home/laeeth/.cache/ipython/pyd/_pyd_magic_7c8a7283575fef42aa3d0f1dc803a275/.dub/build/library-debug-linux.posix-x86_64-dmd_2067-D1EC05E432582762C580ECB068D9114B/ _pyd_magic_7c8a7283575fef42aa3d0f1dc803a275 dynamicLibrary
Error executing command build:
dmd failed with exit code 1.

**Comment by Laeeth** [comment]
Yes - I am!

I needed a @pdef!() for each wrapped member.
But if I am forced to wrap every member, then perhaps they should be automatically wrapped if I don't specify.  Or perhaps I should be allowed not to wrap every member.

I know it's an early stage, but just my thoughts.

**Comment by Laeeth** [comment]
It works fine once I put a @pdef!() for each member  in the struct.

**Comment by John-Colvin** [comment]
Woops. Should be fixed by https://github.com/John-Colvin/ppyd/commit/b750dbd988b353989e3a51c6186f4517d296b0f7 and https://github.com/DlangScience/PydMagic/pull/17

That was a totally avoidable bug, I really need a test suite...

**Comment by Laeeth** [comment]
Thanks.

Re pdef recursive, nice feature to have.  Can you have annotation not to wrap an exceptional member in an otherwise completely wrapped struct ?  (Not an essential feature).

I haven't looked at how code works, but can you have nicer syntax (ie no ! and no brackets if empty).  And maybe recursive is a confusing even if accurate name.

@pywrapall struct S
{
  @pynowrap double onlyD;
  int share;
}
