### ISSUE TITLE
-f doesn't work for me

### ISSUE THREAD

**Issue by Laeeth** [DlangScience/PydMagic#2]
%%pyd -f

import std.stdio;
import std.string;
import std.conv;

@pdef!() string zhello() {
    return "zHello World!";
}

---

TypeError                                 Traceback (most recent call last)
<ipython-input-45-820bd9b79f95> in <module>()
----> 1 get_ipython().run_cell_magic(u'pyd', u'-f', u'\nimport std.stdio;\nimport std.string;\nimport std.conv;\n\n@pdef!() string zhello() {\n    return "zHello World!";\n}\n    \n')

/home/laeeth/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2160             magic_arg_s = self.var_expand(line, stack_depth)
   2161             with self.builtin_trap:
-> 2162                 result = fn(magic_arg_s, cell)
   2163             return result
   2164 

/home/laeeth/.ipython/extensions/pyd_magic.pyc in pyd(self, line, cell)

/home/laeeth/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, _a, *_k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, _a, *_k: f(_a, *_k)
    194 
    195         if callable(arg):

/home/laeeth/.ipython/extensions/pyd_magic.pyc in pyd(self, line, cell)
    163             # Force a new module name by adding the current time to the
    164             # key which is hashed to determine the module name.
--> 165             key += time.time()
    166 
    167         if args.name:

TypeError: can only concatenate tuple (not "float") to tuple

**Comment by John-Colvin** [comment]
fixed by https://github.com/DlangScience/PydMagic/pull/8

feel free to re-open if it persists for you
