### ISSUE TITLE
strangeness with std.net.curl import

### ISSUE THREAD

**Issue by Laeeth** [DlangScience/PydMagic#3]
This fails:
%%pyd -lcurl
import std.stdio;
import std.net.curl;

@pdef!() string test()
{
    download("google.com","/home/laeeth/test.html");
    return "hello";
}

This works:
%%pyd -lcurl
import std.stdio;

@pdef!() string test()
{
    import std.net.curl;
    download("google.com","/home/laeeth/test.html");
    return "hello";
}

Side note - might be good to have some way to have the full output from compiler, as there are so many files for PyD.  When compilation fails one just gets a message it has failed, not the full trace (not sure if capturing stderr).

Laeeth

running build
running build_ext
building '_pyd_magic_decc0785a0314a07cd5f0a31d512cf86' extension
gcc -c /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/d/so_ctor.c -fPIC -o build/temp.linux-x86_64-2.7/infra/so_ctor.o
dmd -c -fPIC -version=PydPythonExtension -version=Python_2_4_Or_Later -version=Python_2_5_Or_Later -version=Python_2_6_Or_Later -version=Python_2_7_Or_Later -version=Python_Unicode_UCS4 -debug -I/home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure -ofbuild/temp.linux-x86_64-2.7/infra/temp.o /home/laeeth/.cache/ipython/pyd/_pyd_magic_decc0785a0314a07cd5f0a31d512cf86.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/class_wrap.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/ctor_wrap.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/def.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/embedded.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/exception.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/extra.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/func_wrap.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/make_object.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/make_wrapper.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/op_wrap.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/pyd.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/pydobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/references.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/struct_wrap.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/pyd/thread.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/util/conv.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/util/typeinfo.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/util/typelist.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/util/multi_index.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/util/replace.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/meta/Demangle.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/meta/Nameof.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/abstract_.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/ast.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/boolobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/bufferobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/bytearrayobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/bytesobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/cellobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/ceval.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/classobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/cobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/codecs.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/code.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/compile.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/complexobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/cStringIO.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/datetime.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/descrobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/dictobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/enumobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/errcode.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/eval.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/fileobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/floatobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/frameobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/funcobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/genobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/grammar.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/import_.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/intobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/intrcheck.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/iterobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/listobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/longintrepr.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/longobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/marshal.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/memoryobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/methodobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/modsupport.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/moduleobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/node.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/object.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/objimpl.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/parsetok.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pgenheaders.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pyarena.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pyatomic.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pycapsule.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pydebug.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pyerrors.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pymem.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pyport.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pystate.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pystrcmp.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pystrtod.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/Python.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pythonrun.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/pythread.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/rangeobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/setobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/sliceobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/stringobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/structmember.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/structseq.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/symtable.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/sysmodule.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/timefuncs.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/traceback.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/tupleobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/unicodeobject.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/deimos/python/weakrefobject.d build/temp.linux-x86_64-2.7/infra/pydmain.d /home/laeeth/anaconda/lib/python2.7/site-packages/pyd/infrastructure/d/python_so_linux_boilerplate.d
An exception has occurred, use %tb to see the full traceback.

SystemExit: error: command 'dmd' failed with exit status 1

Traceback not so useful:
## %tb

SystemExit                                Traceback (most recent call last)
<ipython-input-109-ee6bbf27295a> in <module>()
----> 1 get_ipython().run_cell_magic(u'pyd', u'-lcurl', u'import std.stdio;\nimport std.net.curl;\n\n@pdef!() string test()\n{\n    download("google.com","/home/laeeth/test.html");\n    return "hello";\n}')

/home/laeeth/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2160             magic_arg_s = self.var_expand(line, stack_depth)
   2161             with self.builtin_trap:
-> 2162                 result = fn(magic_arg_s, cell)
   2163             return result
   2164 

/home/laeeth/.ipython/extensions/pyd_magic.pyc in pyd(self, line, cell)

/home/laeeth/anaconda/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, _a, *_k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, _a, *_k: f(_a, *_k)
    194 
    195         if callable(arg):

/home/laeeth/.ipython/extensions/pyd_magic.pyc in pyd(self, line, cell)
    189                 d_lump=True
    190             )
--> 191             pyd.support.setup(ext_modules=[extension],script_name="setup.py",script_args=["build", "--build-lib", lib_dir, "-q", "--compiler="+args.compiler])
    192 
    193         if not have_module:

/home/laeeth/anaconda/lib/python2.7/site-packages/pyd/support.pyc in setup(_args, *_kwargs)
    228         kwargs['cmdclass'] = {}
    229     kwargs['cmdclass']['pydexe'] = build_pyd_embedded_exe
--> 230     base_setup(_args, *_kwargs)

/home/laeeth/anaconda/lib/python2.7/distutils/core.pyc in setup(**attrs)
    164                 raise
    165             else:
--> 166                 raise SystemExit, "error: " + str(msg)
    167 
    168     return dist

SystemExit: error: command 'dmd' failed with exit status 1

**Comment by John-Colvin** [comment]
with the new dub-based system `%%pyd --dub_config={"libs":["curl"]}` makes this work.

**Comment by John-Colvin** [comment]
In fact, if i remember correctly curl is implicitly linked anyway, so just `%%pyd` works
