### ISSUE TITLE
better messages back from compilation process?

### ISSUE THREAD

**Issue by Laeeth** [DlangScience/PydMagic#4]
At the moment there are no error messages for me when compilation fails.  I know that it fails, but not why.  %tb produces traceback on python side, but not stderr during dmd compilation.  I realize it's at an early stage, but worth incorporating when you have more time.

Laeeth.

**Comment by John-Colvin** [comment]
The whole situation with what ends up in the terminal window and what ends up in the cell output needs fixing. It's on my todo-list

**Comment by Laeeth** [comment]
Thanks, John.  It's pretty usable as it is, but this would be a nice refinement.  (I don't think I see a terminal - any tips to make it show).
I can imagine if you're busy you might have mixed feelings about the nuisance caused by releasing it when people start to use it and want
changes when you don't have time - so I appreciate your releasing, and no hurry on anything.  If I can, I will try to figure out myself when
time.

The other thing is at the moment it's a pain if you want to use vibed and any projects built with dub.  So some way to either use dub with
the -v to figure out the build and automatically reverse engineer it, or use dub as a library, or specify the pyd+pydmagic files in dub
format would be of benefit in the medium term.  I tried and failed on first two attempts (not to write this, but just to build using dub) but
will get there eventually; for other people, especially newcomers, there may be value in making this easy.

I will spend a bit more time trying to figure it out.

Laeeth

**Comment by John-Colvin** [comment]
when i say "terminal window" i mean the terminal window from which you launched ipython.

Hopefully I'll get to take a look at this today

**Comment by Laeeth** [comment]
Aha!  I didn't explicitly check, but don't recall seeing compiler output in that window.

Russell's message on the forum was a perfect example of how even for clever and experienced people small frictions may have large consequences...

**Comment by John-Colvin** [comment]
This should now be fixed. Compiler output is dumped to the notebook if compilation fails.
